Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
  Customname:
    Type: String
    Description: User name
    MinLength: '1'
    MaxLength: '41'

Resources:
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref 'Password'
      ManagedPolicyArns: 
        - !Ref CFNUserPolicies
      UserName: !Ref Customname  
 
  CFNUserPolicies:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: User S3 Policy
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - 's3:GetAccelerateConfiguration'
              - 's3:GetAccountPublicAccessBlock'
              - 's3:GetAnalyticsConfiguration'
              - 's3:GetBucketAcl'
              - 's3:GetBucketCORS'
              - 's3:GetBucketLocation'
              - 's3:GetBucketLogging'
              - 's3:GetBucketNotification'
              - 's3:GetBucketPolicy'
              - 's3:GetBucketPolicyStatus'
              - 's3:GetBucketPublicAccessBlock'
              - 's3:GetBucketRequestPayment'
              - 's3:GetBucketTagging'
              - 's3:GetBucketVersioning'
              - 's3:GetBucketWebsite'
              - 's3:GetEncryptionConfiguration'
              - 's3:GetInventoryConfiguration'
              - 's3:GetLifecycleConfiguration'
              - 's3:GetMetricsConfiguration'
              - 's3:GetObjectAcl'
              - 's3:GetObjectTagging'
              - 's3:GetObjectTorrent'
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
              - 's3:GetObjectVersionForReplication'
              - 's3:GetObjectVersionTagging'
              - 's3:GetObjectVersionTorrent'
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
              - 's3:ListBucketByTags'
              - 's3:ListBucketMultipartUploads'
              - 's3:ListBucketVersions'
              - 's3:ListJobs'
              - 's3:ListMultipartUploadParts'
              - 's3:ListAllMyBuckets'
            Effect: Allow
            Resource: ['arn:aws:s3:::*']

 



  